---
- name: Play mysql server setup
  hosts: mysql_host
  tasks:
      - name: Install the mariadb-server
        when: ansible_os_family == "RedHat"
        yum:
          name: mariadb-server
          state: present
        become: true

      - name:  Service is running
        service:
          name: mariadb
          state: started
        become: true

      - name: Copy init.sql file
        template:
          src: ../files/mysql/init.sql.j2
          dest: /var/local/mysql-init.sql
        become: true

      - name: init database once
        shell: mysql -uroot -e 'SHOW DATABASES;' | grep otus
        register: has_otus_database
        ignore_errors: true

      - name: init database `otus` once
        shell: mysql -uroot < /var/local/mysql-init.sql
        when: has_otus_database.stdout == ""

      - debug:
          var: has_otus_database.stdout
