# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'open3'
require 'fileutils'

Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|
    config.vm.box = 'almalinux/8'

    server.vm.host_name = 'server'
    server.vm.network :private_network, type: "dhcp"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    server.vm.provision "shell",  name: "configuration", path: "init.sh"
  end

  config.vm.define "client" do |client|
    client.vm.box = 'almalinux/8'
    client.vm.host_name = 'client'
    client.vm.network :private_network, type: "dhcp"
    client.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end

end
