# https://docs.docker.com/engine/install/centos/
# https://docs.docker.com/engine/install/linux-postinstall/
# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04

---
- name: Play docker
  hosts: log
  tasks:
    - name: Install requirements for RedHat family
      when: ansible_os_family == "RedHat"
      block:
        - name: Remove podman
          yum:
            update_cache: true
            pkg:
              - podman
              - buildah
            state: absent
          become: true

        - name: Download docker repo
          get_url:
            url: https://download.docker.com/linux/centos/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo
          become: true

        - name: Install docker
          yum:
            pkg:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose
              - docker-compose-plugin
          become: true

        - name: Running docker service
          service:
            name: docker
            state: started
          become: true

    - name: Install requirements for Debian family
      when: ansible_os_family == "Debian"
      block:
        - name: Add Docker GPG apt Key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
          become: true

        - name: Add Docker Repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu focal stable
            state: present
          become: true

        - name: Install docker
          apt:
            update_cache: true
            pkg:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose
              - docker-compose-plugin
            state: latest
          become: true

    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present
      become: true

    - name: adding current user "{{ ansible_user_id }}" to group "docker"
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
      become: true

    - name: Ensure docker service is running
      service:
        name: docker
        state: started
        enabled: true
      become: true

    - name: Install docker-compose for Debian family
      when: ansible_os_family == "Debian"
      block:
        - name: Add Docker GPG apt Key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

