---
- name: Install python3 pip
  hosts: all
  tasks:
    - name: Install pip for RedHat family
      when: ansible_os_family == "RedHat"
      yum:
        name: python3-pip
        state: present
        update_cache: true
      become: true

    - name: Install pip for Debian family
      when: ansible_os_family == "Debian"
      apt:
        name: python3-pip
        state: present
        update_cache: true
      become: true
