# https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html
# https://www.elastic.co/guide/en/kibana/current/docker.html

version: '3.1'
services:
  es:
    image: elasticsearch:8.5.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es-node
      - cluster.name=es-docker-cluster
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

#  logstash:
#    image: logstash:8.5.3
#    restart: unless-stopped

  kibana:
    image: kibana:8.5.3
    restart: unless-stopped
    ports:
      - "5601:5601"
    volumes:
      - kibana-data:/usr/share/kibana/data

volumes:
  es-data: ~
  kibana-data: ~
