Vagrant.configure("2") do |config|

   config.vm.define "main" do |node|
    node.vm.network "private_network", ip: "192.168.56.20"
    node.vm.box = 'ubuntu/jammy64'
    node.vm.network :private_network, type: "dhcp"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "main_play.yaml"
    end
  end

  config.vm.define "node1" do |node|
    node.vm.network "private_network", ip: "192.168.56.21"
    node.vm.box = 'ubuntu/jammy64'
    node.vm.network :private_network, type: "dhcp"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "node_play.yaml"
    end
  end

  config.vm.define "node2" do |node|
    node.vm.network "private_network", ip: "192.168.56.22"
    node.vm.box = 'almalinux/8'
    node.vm.network :private_network, type: "dhcp"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
#    node.vm.provision "ansible" do |ansible|
#      ansible.playbook = "node_play.yaml"
#    end
  end

end
