Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/8"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.network :private_network, ip: '192.168.56.10'

  config.vm.provision "shell", name: "init", path: "vagrant_init.sh"
end
