# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

 config.vm.box = "centos/7"

 config.vm.define "server" do |server|
  server.vm.hostname = "server"
  server.vm.network "private_network", ip: "192.168.60.10", virtualbox__intnet: true

  server.vm.provision "ansible" do |ansible|
    ansible.playbook = "server_play.yaml"
  end

 end

 config.vm.define "client" do |client|
  client.vm.hostname = "client"
  client.vm.network "private_network", ip: "192.168.60.20", virtualbox__intnet: true

  client.vm.provision "ansible" do |ansible|
    ansible.playbook = "client_play.yaml"
  end

 end

 config.vm.define "ras_server" do |box|
  box.vm.hostname = "ras.server"

  box.vm.network "private_network", ip: "192.168.60.30", virtualbox__intnet: true
  box.vm.network "private_network", ip: "192.168.62.10"

  box.vm.provision "ansible" do |ansible|
    ansible.playbook = "ras_server_play.yaml"
  end

 end

end
