Vagrant.configure(2) do |config|

  config.vm.define "server" do |box|
    box.vm.box = "almalinux/8"
    box.vm.hostname = "server.ldap.local"
    box.vm.network :private_network, ip: "192.168.60.10"
    box.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "play_server.yaml"
    end

  end

  config.vm.define "client" do |box|
    box.vm.box = "almalinux/8"
    box.vm.hostname = "client.ldap.local"
    box.vm.network :private_network, ip: "192.168.60.11"
    box.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "play_client.yaml"
    end

  end

end
