vagrant_nodes:
    vars:
        ansible_ssh_user: vagrant
    hosts:
        nginx_host:
            ansible_host: "{{ nginx_node.host }}"
            ansible_ssh_private_key_file: ./.vagrant/machines/nginx_node/virtualbox/private_key
        php_host:
            ansible_host: "{{ php_node.host }}"
            ansible_ssh_private_key_file: ./.vagrant/machines/php_node/virtualbox/private_key
        mysql_host:
            ansible_host: "{{ mysql_node.host }}"
            ansible_ssh_private_key_file: ./.vagrant/machines/mysql_node/virtualbox/private_key
