global:
  scrape_interval: 5s
  evaluation_interval: 15s
  query_log_file: /prometheus/query.log

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

scrape_configs:
- job_name: nodes
  static_configs:
    - targets:
        - '192.168.56.21:9100'
        - '192.168.56.22:9100'

